<?php

namespace Bigfoot\Bundle\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataRepository extends EntityRepository
{
}
